version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: git clone https://github.com/contentful/the-example-app-e2e-tests.git ./test/e2e
      - run: cd ./test/e2e && npm install
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "test/e2e/package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
            - test/e2e/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "test/e2e/package.json" }}
      - run: npm test
      - store_artifacts:
          path: cypress
workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
