---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nodesample-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: nodesample-prod
  chart:
    git: git@github.com:kunrad/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      repository: kunrad/the-example-app.nodejs
      tag: 0.4.11
    replicaCount: 3
